# Generated by Django 3.1.2 on 2020-10-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='content_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='extension',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
