# Generated by Django 3.1.2 on 2020-10-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20201005_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='clave',
            new_name='key',
        ),
    ]
