# Generated by Django 3.1.2 on 2020-10-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('images', '0003_auto_20201006_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
        ),
    ]
