# Generated by Django 3.1.2 on 2020-10-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='title',
        ),
    ]
