# Generated by Django 3.1.2 on 2020-10-11 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20201011_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='extension',
        ),
    ]
