# Generated by Django 3.1.2 on 2020-10-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20201011_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
